### ISSUE TITLE
Submitting the app for review: did nothing but return success

### ISSUE THREAD

**Issue by dral3x** [fastlane/deliver#360] opened 2015-09-30 10:03 UTC
I already reported this problem in [here](https://github.com/KrauseFx/deliver/issues/337#issuecomment-144048214) but I think it's a big issue.

`Submit for review` does not work and in the worst possible way.
It does nothing (the app state still `Prepare for submission`) and terminates reporting a success.

```
[14:23:45]: [SHELL]: [14:23:35]: Finished the upload to iTunes Connect
[14:23:45]: [SHELL]: [14:23:35]: Selecting the latest build...
[14:23:45]: [SHELL]: [14:23:37]: Selecting build 1.5.3 (3703)...
[14:23:45]: [SHELL]: [14:23:38]: Successfully selected build
[14:23:45]: [SHELL]: [14:23:38]: Submitting the app for review...
[14:23:45]: [SHELL]: [14:23:45]: Successfully submitted the app for review!
```

Maybe the only thing it does is select the available build (already processed by Apple) but that's it.
It also "succeed" if the the build still processing.

Thanks

**Comment by PeterCen** [comment] 2015-09-30 19:33
+1 Same here, I'm trying to see if it works by making the request in Paw

**Comment by PeterCen** [comment] 2015-09-30 21:24
I managed to get it to work by making these changes:

1. Adding the  --force --submit_for_review flag to deliver  
2. In my DeliverFile, use the following format
submit_for_review({
   export_compliance_available_on_french_store: false,
   export_compliance_ccat_file: false,
   export_compliance_contains_proprietary_cryptography: false,
   export_compliance_contains_third_party_cryptography: false,
   export_compliance_is_exempt: false,
   export_compliance_uses_encryption: false,
   export_compliance_app_type: false,
   export_compliance_encryption_updated: false,
   export_compliance_compliance_required: false,
   export_compliance_platform: false,
   content_rights_contains_third_party_content: true,
   content_rights_has_rights: true,
   add_id_info_limits_tracking: false,
   add_id_info_serves_ads: false,
   add_id_info_tracks_action: false,
   add_id_info_tracks_install: false,
   add_id_info_uses_idfa: false
 })
3. Setting the name in the metadata in my Deliver file.

I will keep testing and try to debug which one is causing the issue, but it seems that the iTC API returns 200 even if it didn't successfully submit the app

**Comment by dral3x** [comment] 2015-10-01 07:54
Interesting. I will try this out too

**Comment by PeterCen** [comment] 2015-10-01 08:09
line 90 in app_submission.rb of spaceship 

```'exportCompliance.encryptionUpdated' => :export_compliance_encryption_updated,```

should be 

```'exportCompliance.encryptionUpdated.value' => :export_compliance_encryption_updated,```

**Comment by dral3x** [comment] 2015-10-01 08:18
No luck on my side. I was just able to not crash deliver by passing no parameter to `submission_information`

```
submission_information({
  # All is false by default
})
```

Any tests ends with this error (I suppose related to the thing @PeterCen posted here)

Error converting JSON string to object: Can not instantiate value of type [simple type, class com.apple.jingle.label.to.LCFieldTO<java.lang.String>] from JSON String; no single-String constructor/factory method (through reference chain: com.apple.jingle.label.content.purple.to.LCSubmitForReviewTO["exportCompliance"]->com.apple.jingle.label.content.purple.to.LCExportComplianceTO["encryptionUpdated"])

**Comment by PeterCen** [comment] 2015-10-01 08:23
That error is due to the spaceship line 90, exportCompliance.encryptionUpdated should be a JSON object but putting "false" changes the value directly therefore iTC returns that error since it's expecting a JSON object instead of a string. Changing the line to exportCompliance.encryptionUpdated.value sets the correct field "value" inside of encryptionUpdated.

**Comment by OlKir** [comment] 2015-10-08 09:29
I can confirm that fix of spaceship in line 90 worked for me - app was successfully sent in to review. I hope it will be included to main project soon.

**Comment by KrauseFx** [comment] 2015-10-08 14:17
If you let me know what I have to change I'm happy to make the change in `spaceship` @PeterCen 

I now have
```ruby
attr_mapping({
        # Ad ID Info Section
        'adIdInfo.limitsTracking.value' => :add_id_info_limits_tracking,
        'adIdInfo.servesAds.value' => :add_id_info_serves_ads,
        'adIdInfo.tracksAction.value' => :add_id_info_tracks_action,
        'adIdInfo.tracksInstall.value' => :add_id_info_tracks_install,
        'adIdInfo.usesIdfa.value' => :add_id_info_uses_idfa,

        # Content Rights Section
        'contentRights.containsThirdPartyContent.value' => :content_rights_contains_third_party_content,
        'contentRights.hasRights.value' => :content_rights_has_rights,

        # Export Compliance Section
        'exportCompliance.availableOnFrenchStore.value' => :export_compliance_available_on_french_store,
        'exportCompliance.ccatFile.value' => :export_compliance_ccat_file,
        'exportCompliance.containsProprietaryCryptography.value' => :export_compliance_contains_proprietary_cryptography,
        'exportCompliance.containsThirdPartyCryptography.value' => :export_compliance_contains_third_party_cryptography,
        'exportCompliance.isExempt.value' => :export_compliance_is_exempt,
        'exportCompliance.usesEncryption.value' => :export_compliance_uses_encryption,
        'exportCompliance.appType' => :export_compliance_app_type,
        'exportCompliance.encryptionUpdated' => :export_compliance_encryption_updated,
        'exportCompliance.exportComplianceRequired' => :export_compliance_compliance_required,
        'exportCompliance.platform' => :export_compliance_platform
      })
```
in `app_submission.rb`

**Comment by PeterCen** [comment] 2015-10-08 14:26
@KrauseFx 

The change is

```
'exportCompliance.encryptionUpdated' => :export_compliance_encryption_updated
```

to

```
'exportCompliance.encryptionUpdated.value' => :export_compliance_encryption_updated
```

I've made a pull request, but it's probably easier for you to just change it!

**Comment by KrauseFx** [comment] 2015-10-08 14:39
Thanks @PeterCen :+1:

**Comment by KrauseFx** [comment] 2015-10-08 14:43
Please update `spaceship` to https://github.com/fastlane/spaceship/releases/tag/0.11.4 using `sudo gem update spaceship` :rocket:

**Comment by PeterCen** [comment] 2015-10-08 17:19
@KrauseFx No problem!

Also, the format of the submission_information is also pretty information for the whole submit to work. I suggest adding the information to DeliverFile.md and the current suggested format can cause issues as iTC expects "false" instead of false for some of the values. From looking at the POST request on iTC, the following are the expected value formats.

```
export_compliance_available_on_french_store: "false",
   export_compliance_contains_proprietary_cryptography: "false",
   export_compliance_contains_third_party_cryptography: "false",
   export_compliance_is_exempt: "false",
   export_compliance_uses_encryption: "false",
   export_compliance_app_type: nil,
   export_compliance_encryption_updated: "false",
   export_compliance_compliance_required: "false",
   export_compliance_platform: "ios",
   content_rights_contains_third_party_content: "true",
   content_rights_has_rights: "true",
   add_id_info_limits_tracking: "false",
   add_id_info_serves_ads: "false",
   add_id_info_tracks_action: "false",
   add_id_info_tracks_install: "false",
   add_id_info_uses_idfa: "false"
```

**Comment by amenon** [comment] 2015-10-12 15:26
I'm still seeing this issue with `spaceship v0.11.5` running `deliver --submit_for_review` from the command line (without a Deliverfile). The IPA gets uploaded and processed, and `deliver` waits for it to be processed before printing out the success message on the console.

Please let me know if there is something I can do to help diagnose the issue.

**Comment by pedro380085** [comment] 2015-10-20 15:35
:+1:

**Comment by builder1278** [comment] 2015-11-28 21:21
Hi,
I guess it is necessary to change line 91 in app_submission.rb too. The same as line 90 (Boolean).
For me --submit_for_review for very first version doesn't work. Could be the reason?
Thanks

**Comment by maciekish** [comment] 2015-12-02 22:55
@KrauseFx I think i have a related issue. When `Spaceship::Tunes.client.submit_testflight_build_for_review!(parameters)` tries to assign `encryption_info['encryptionUpdated']['value']` it turns out that `encryption_info['encryptionUpdated']` is nil at https://github.com/fastlane/spaceship/blob/master/lib/spaceship/tunes/tunes_client.rb#L580

`encryption_info` at this stage is:

    {
		"sectionErrorKeys": [
				
		],
		"sectionInfoKeys": [
				
		],
		"sectionWarningKeys": [
				
		],
		"usesEncryption": {
				"value": true,
				"isEditable": true,
				"isRequired": false,
				"errorKeys": null
		},
		"encryptionUpdated": null,
		"isExempt": {
				"value": null,
				"isEditable": true,
				"isRequired": false,
				"errorKeys": null
		},
		"containsProprietaryCryptography": {
				"value": null,
				"isEditable": true,
				"isRequired": false,
				"errorKeys": null
		},
		"containsThirdPartyCryptography": {
				"value": null,
				"isEditable": true,
				"isRequired": false,
				"errorKeys": null
		},
		"availableOnFrenchStore": {
				"value": null,
				"isEditable": true,
				"isRequired": false,
				"errorKeys": null
		},
		"ccatFile": {
				"value": null,
				"isEditable": true,
				"isRequired": false,
				"errorKeys": null
		},
		"appType": null,
		"platform": "ios",
		"exportComplianceRequired": true,
		"usesNonExemptEncryptionFromPlist": null,
		"status": null,
		"builds": null,
		"storeVersions": null,
		"codeValue": null,
		"id": null,
		"uploadDate": 0
    }

**Closed** 2016-03-07 18:33 UTC
Labels: migrated
